### ISSUE TITLE
Not a bug, just a hi!

### ISSUE THREAD

**Issue by m9dfukc** [yohasebe/deepl-alfred-translate-rewrite-workflow#2]
Hi,

jfyi I try to forward the users of [my Alfred Deepl Workflow](https://github.com/m9dfukc/deepl-alfred-workflow) to yours ... unfortunately mine broke a while ago when Deepl changed policies and restricted their unofficial API.

**Comment by yohasebe** [comment]
Thank you for your message. I hope some of the users of your workflow find mine useful too.
