### ISSUE TITLE
A typo in deepl-usage

### ISSUE THREAD

**Issue by ghost** [yohasebe/deepl-alfred-translate-rewrite-workflow#3]
Dee**l**pL Ch**a**ck Usage Information should be DeepL Check Usage Information. Cheers :)

**Comment by yohasebe** [comment]
Sorry for the belated reply. Thank you so much for reporting this stupid typo! I fixed it.

**Comment by ghost** [comment]
No worries, since it was insanely minor anyway :P Anyway, リポートにどういたしまして＆フィクスにありがとう (^^)
