### ISSUE TITLE
Sometimes receiving "ERROR: Input text is empty"

### ISSUE THREAD

**Issue by jmuheim** [yohasebe/deepl-alfred-translate-rewrite-workflow#5]
I have specified a hotkey:

![CleanShot 2022-09-16 at 09 14 23@2x](https://user-images.githubusercontent.com/1814983/190579012-4f658c3d-0429-424d-b19c-088c30c37220.png)

I select a text in my browser:

![CleanShot 2022-09-16 at 09 15 34@2x](https://user-images.githubusercontent.com/1814983/190579205-b955f501-8716-413f-9ded-808b059b1fdb.png)

I press **`Ctrl`+`Option`+`Command`+`D`**, and (most of the times) I receive this error:

<img width="1263" alt="CleanShot 2022-09-16 at 09 12 32@2x" src="https://user-images.githubusercontent.com/1814983/190578707-c8efc1aa-7daa-4d8e-84ad-2f5d6f175a2e.png">

In rare cases, the translation works as expected. And when using the default Alfred input (i.e. `deepl This is a test`, then **`Enter`)**, it always works:

![image](https://user-images.githubusercontent.com/1814983/190580001-95192166-1710-4f46-86cb-b6a3c6318502.png)

How to fix?

**Comment by yohasebe** [comment]
Version 1.2.2 has been released. In this version, I added `wait_before_selection` variable with a default value of 0.5 (seconds). You may want to increase the value in case you still get an "input text is empty" error. Thanks for your report!

**Comment by jmuheim** [comment]
Works much better, thank you!
