### ISSUE TITLE
Values for formality?

### ISSUE THREAD

**Issue by jmuheim** [yohasebe/deepl-alfred-translate-rewrite-workflow#6]
What values does the `formality` variable allow? I can't find anything in the README.

**Comment by yohasebe** [comment]
[This page](https://www.deepl.com/docs-api/translate-text/translate-text) has information about `formality`. It says:

> Sets whether the translated text should lean towards formal or informal language. This feature currently only works for target languages `DE` (German), `FR` (French), `IT` (Italian), `ES` (Spanish), `NL` (Dutch), `PL` (Polish), `PT-PT`, `PT-BR` (Portuguese) and `RU` (Russian). Possible options are:
> 
> `default` (default)
> `more` - for a more formal language
> `less` - for a more informal language

I hope this option to work in more languages in the future.

**Comment by jmuheim** [comment]
Thanks for this. 👍
