### ISSUE TITLE
"formality" doesn't change the primary language

### ISSUE THREAD

**Issue by ShaoyuWang1** [yohasebe/deepl-alfred-translate-rewrite-workflow#7]
I set formality as "ZH" (Chinese) but the translated text is still in Japanese

**Comment by yohasebe** [comment]
The `formality` option is not available for Chinese (`ZH`). Also, `formality` must be either `default`, `more`, or `less`. (https://www.deepl.com/en/docs-api/translate-text/translate-text) 

If your first language is Chinese and the target language is English, for instance, set `primary_lang` to `ZH` and `secondary_lang` to `EN`.

**Comment by ShaoyuWang1** [comment]
Thanks! It works, I misunderstood the formality and primary_lang last night.

BTW, I think it would be great to show the preview of the translation result in the Alfred menu. Using \<items\> maybe? This would be convenient, especially for the translation of short phrases.

[<img src="https://cdn.mathpix.com/snip/images/AvqJ2UBdHzJX5TFUrJPvCJZuEXVRQXBnERqLX6QPdBU.original.fullsize.png" />
](https://res.cloudinary.com/dno1beosk/image/upload/v1665195848/alfred_sample_uiidf4.png)

 I tried to add it to this workflow, but I'm not quite familiar with ruby script.

**Comment by yohasebe** [comment]
Considering that one translated text is given back in response to an API call and that one single API call takes some time before it finishes, it would be a bit difficult to make it a useful functionality. Still, thank you for your suggestion.
