### ISSUE TITLE
What is the environment variable "speak" for?

### ISSUE THREAD

**Issue by jmuheim** [yohasebe/deepl-alfred-translate-rewrite-workflow#8]
Can the extension actually speak?

Thanks for creating and maintaining this very useful extension. 🙂 I use it nearly every single day.

**Comment by yohasebe** [comment]
Thank you for your kind words 😊

Your question made me realize that I had previously introduced the `speak` environment variable, but had not added the functionality that actually used it. 

In the latest version (1.5.2), if you set the environment variable `speak` to `true`, the response will be read out in the language set as "system speech language" on the Mac. 

I also added a section on [Text to Speech](https://github.com/yohasebe/deepl-alfred-translate-rewrite-workflow#text-to-speech) to the README. 

Enjoy!

**Comment by jmuheim** [comment]
Thank you, I will give it a try! 🙂
